server:
  port: ${PORT:0}

spring:
  application:
    name: hr-payroll

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka

ribbon:
  ConnectionTimeOut: 2000
  ReadTimeOut: 4000