server:
  port: 8765

spring:
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka

zuul:
  routes:
    #hr-oauth
    oauth:
      service-id: hr-oauth
      path: /hr-oauth/**
      sensitive-headers: Cookie, Set-Cookie
    #hr-worker
    worker:
      service-id: hr-worker
      path: /hr-worker/**
    #hr-payment
    payroll:
      service-id: hr-payroll
      path: /hr-payroll/**
    #hr-user
    user:
      service-id: hr-user
      path: /hr-user/**