server:
  port: 9001

spring:
  application:
    name: hr-worker
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testedb
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka