server:
  port: 8888

spring:
  application:
    name: hr-config-server
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/nelsonreisneto/microservices-udemy.git
          search-paths: configs
          username: nelsonr.neto@hotmail.com
          password: N3t0@1608
